# Generated by Django 2.2.7 on 2022-05-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Konsolt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('', '')], max_length=30, null=True),
        ),
    ]
